AWSTemplateFormatVersion: 2010-09-09
Description: |

Resources:
  #----------Bucket ---------------------
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: kittens3.origindev.click

      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

      Tags:
        - Key: Name
          Value: kittens-cloudformation
      VersioningConfiguration:
        Status: Enabled
      WebsiteConfiguration:
        IndexDocument: index.html
  #----------Bucket Policy-----------

  SampleBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref MyS3Bucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - "s3:GetObject"
            Effect: Allow
            Resource: !Join
              - ""
              - - "arn:aws:s3:::"
                - !Ref MyS3Bucket
                - /*
            Principal: "*"
            Sid: PublicReadGetObject

  #----------cloudfront-distro and tab-----------

  CloudFrontDistro:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - !Ref MyS3Bucket

        #----------Find the dafault cache behaivour

        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
          ForwardedValues: #-------Forwarded valued from doc
            Cookies:
              Forward: none

            QueryString: true # enable true

          TargetOriginId: KittensOrigin # give a name

          ViewerProtocolPolicy: allow-all

        DefaultRootObject: index.html
        Enabled: true # enable true
        HttpVersion: http2 # or http2

        Origins: # Grab from origins for cloudformation
          - CustomOriginConfig:
              OriginProtocolPolicy: http-only
            DomainName: kittens3.origindev.click.s3-website.us-east-1.amazonaws.com
            Id: KittensOrigin
        ViewerCertificate:
          AcmCertificateArn: arn:aws:acm:us-east-1:767397930920:certificate/bb0d2152-253b-481a-bbd8-42b73ee05f62
          SslSupportMethod: sni-only
  MyDNSRecord:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId: Z084333435N40BVFRMK4F
      RecordSets: # Grab record sets form cloudformation doc
        - AliasTarget:
            DNSName: !GetAtt CloudFrontDistro.DomainName
            HostedZoneId: Z2FDTNDATAQYW2
          Name: !Ref MyS3Bucket
          Type: A

Outputs:
  S3WebsiteURL:
    Description: Information about the value
    Value: !GetAtt MyS3Bucket.WebsiteURL

  FullyQualifiedDomainName:
    Description: FQDN
    Value: !Ref MyS3Bucket
